backupFolder: "backups"
# Maximum backup size in Gigabyte
maxBackupFolderSize: 10
excludeFiles: []
# Upload section
# Possible value sftp, if empty the backup won't be uploaded
uploadProtocol: ""
hostname: ""
port: 22
username: ""
# Password or private RSA Key without password for SFTP
# It's recommended to use a dedicated RSA key pair for SFTP
authentication: ""
# For SFTP only
# Either the path of the knownHosts file or the RSA HostKey
knownHosts: ""
# Timeout in seconds
timeout: 20
# Make sure the remote directory already exists
remoteDirectory: "myServerBackups"
# Duration between backups, see more examples at:
# https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/time/Duration.html#parse(java.lang.CharSequence)
duration: "P1D"
