main: me.zombie_striker.sr.Main
version: 1.1.4
name: SecureServerBackup
api-version: 1.16
commands:
  SecureServerBackup:
    description: Saves the server
    aliases: [ssb]
permissions:
  secureserverrestorer.*:
    description: Gives access to all PixelPrinter commands
    children:
      secureserverbackup.save: true
      secureserverbackup.command: true
      secureserverbackup.login: true
author:
  KastenKlicker
